INDIGO_WELCOME_MESSAGE: "The place for all your online learning"
INDIGO_PRIMARY_COLOR: "#5c0e81" # cool blue

# Footer links are dictionaries with a "title" and "url"
# To remove all links, write:
# INDIGO_FOOTER_NAV_LINKS: []
# INDIGO_FOOTER_LEGAL_LINKS: []
INDIGO_FOOTER_NAV_LINKS:
  - title: "About"
    url: "https://www.empowrco.org/our-vision"
  - title: "Contact Us"
    url: "https://www.empowrco.org/contact-us"
  - title: "Donate"
    url: "https://www.empowrco.org/donate"
INDIGO_FOOTER_LEGAL_LINKS:
  - title: "Terms of service"
    url: "/tos"
  - title: "Privacy Policy"
    url: "/privacy"
