INDIGO_WELCOME_MESSAGE: "The place for all your online learning"
INDIGO_PRIMARY_COLOR: "#5D0E81" # cool blue

# Footer links are dictionaries with a "title" and "url"
# To remove all links, write:
# INDIGO_FOOTER_NAV_LINKS: []
# INDIGO_FOOTER_LEGAL_LINKS: []
INDIGO_FOOTER_NAV_LINKS:
  - title: "About"
    url: "/about"
INDIGO_FOOTER_LEGAL_LINKS:
    - title: "Terms of service"
      url: "/tos"
